//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expression
    {
        public int Id { get; set; }
        public Nullable<int> CommentId { get; set; }
        public Nullable<bool> isLike { get; set; }
        public Nullable<bool> isUnlike { get; set; }
    
        public virtual Commnet Commnet { get; set; }
    }
}
